### ISSUE TITLE
[QUESTION] Get Gold seems impossible

### ISSUE THREAD

**Issue by SundanceOwl** [MundM2007/Ultimate-Progression-Sky#11]
**Question**
...maybe im wrong, but you cant get the iron mesh, for sieving gold. As far as i have seen, the only way to get your first gold is to sieve with an iron mesh. And the iron mesh is only produced through the create building process. Im up to the building machine, set up a 3x3 square, but cant use it properly, because the wrench for setting up the single units correctly is hiding behind a goldplate, so it seems impossible. 

Maybe its just another clever idea and i have to search the gold from anywhere else in another mod, then its a very smart idea and i have to solve it. But if its unintentional in the progression, then here its a stuck problem.

Otherwise i enjoy the modpack very much. Many clever ideas

**Comment by MundM2007** [comment]
You can also build the create 3x3 crafters by looking at the Block where it should face to. So If you place a crafter on the Block there is another crafter, the crafter will point into that other crafter. Using this you can build and connect the crafters and craft the iron mesh.
