### ISSUE TITLE
I can't launch modpack

### ISSUE THREAD

**Issue by GrishaCrysta** [MundM2007/Ultimate-Progression-Sky#12]
During loading, when I click on the window, it says that it is not responding, but the text still appears. When the text disappears, the memory used slowly increases (approximately MB in 5 seconds). It never made it past the loading stage (with the anvil)
OS: Windows 11
Allocated memory: 15 GB
System RAM: 32 GB
CPU: i5 10500H
GPU: RTX 3050
Type of PC: laptop

**Comment by MundM2007** [comment]
Pleased don't click on the Game during loading.
Also 15 GB is to high you shouldn't need more than 12 to start. (To high memory can actually hurt performance) the Game Takes time to load and when clicking Windows then thinks it isn't responding. So try without clicking on the Screen and Just let it Rest for a bit.

**Comment by GrishaCrysta** [comment]
Ok, wait please. And I started game with 10 GB RAM, and error code was -1073740791. I didn't clicked on window

**Comment by GrishaCrysta** [comment]
It still does not load and the same thing happens (adding mb every few seconds), only now it is slowly being reset

**Comment by GrishaCrysta** [comment]
I think it isn't normal.
P.S. it  still didn't finish loading

**Comment by MundM2007** [comment]
Then pleased Open your modpack folder and then Go into the logs folder and upload latest.log here.

**Comment by GrishaCrysta** [comment]
[latest.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/10325372/latest.log)

**Comment by MundM2007** [comment]
Can you try re-installing the modpack again by or deleting and installing again.
Just to have another error source removed

**Comment by GrishaCrysta** [comment]
Yes, I can

**Comment by GrishaCrysta** [comment]
Situation is same

**Comment by MundM2007** [comment]
Sorry for taking so long, but i have two questions:
what launcher are you using?
and have you added anything to the pack?

**Comment by GrishaCrysta** [comment]
I used curseforge launcher, the one that turns on when you press the play button.

**Comment by GrishaCrysta** [comment]
No, I didn't add anything

**Comment by MundM2007** [comment]
Found this somewhere: try updating to java version 1.8.0_161 (still java 8) or higher (maybe also latest)

**Comment by GrishaCrysta** [comment]
I will install java ver 8 update 351

**Comment by GrishaCrysta** [comment]
Error code: 1

**Comment by GrishaCrysta** [comment]
Vanila mine succesfully runned (launcher from microsoft)

**Comment by GrishaCrysta** [comment]
Modpack 1.16.5 with 400+ mods succesfully runned

**Comment by MundM2007** [comment]
send new log

**Comment by GrishaCrysta** [comment]
[latest.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/10337797/latest.log)

**Comment by MundM2007** [comment]
you would also need to change the java version used in curseforge launcher.

**Comment by GrishaCrysta** [comment]
Error code: 1

**Comment by MundM2007** [comment]
error codes are useless, would need the log again

**Comment by GrishaCrysta** [comment]
[latest.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/10367918/latest.log)

**Comment by GrishaCrysta** [comment]
uhhhh... where are you?

**Comment by MundM2007** [comment]
still uses the old java version, btw if the different java version doesn't work i have no other idea, you can see the java version in the second line of the log

**Comment by GrishaCrysta** [comment]
I tried to launch by ftb launcher, and it succesfully launched

**Comment by GrishaCrysta** [comment]
I tried to launch by ftb launcher, and it succesfully launched
