### ISSUE TITLE
[BUG] The mods Packagedauto and Packagedexcrafting can free acquisition of goods with Carryon

### ISSUE THREAD

**Issue by half-nothing** [MundM2007/Ultimate-Progression-Sky#13]
**Describe the bug**
If I put something in ```packagedauto:packager``` and use the mod Carry On. I can duplicate item.

**To Reproduce**
1. Put down  ```packagedauto:packager``` or something else you can put something in.
2. Put something you want to copy in.
3. Shitf + Right click on the block.
4. Right click on block.
5. You can see the error in the chat bar. 
6. Run command ```/carryon clear```.
7. Open the block and take out the item

**Expected behavior**
![image](https://user-images.githubusercontent.com/50048293/210534410-77e0a112-132b-46c0-bdfc-c14e7e501c5b.png)

**Screenshots**
I made a video.
https://user-images.githubusercontent.com/50048293/210534784-b2a6ac63-8cce-4561-be77-0b359ea9c79d.mp4

**Versions (please complete the following information):**
- Modpack version: The latest
- Server?: Yes

**Additional context**
We delete the mod ```ChunkLoader```
This is a minor bug and can be fixed by editing carryon's configuration file

**Comment by MundM2007** [comment]
will only be fixed on new worlds

**Comment by half-nothing** [comment]
> will only be fixed on new worlds

What did you mean?
If you mean I must create a new world so it can be fixed, I don't think that's quite true.Because I have tried in my server where it actually works.

**Comment by MundM2007** [comment]
Without modifying the world file it will not take affect. You can obviously Edit the serverconfig, for it to be fixed, but it wont do it automatically
