### ISSUE TITLE
[CRASH] ...

### ISSUE THREAD

**Issue by Arclesis420** [MundM2007/Ultimate-Progression-Sky#2]
**Describe the Crash**
Just Started the pack and while looking in the quest book after i clicked on Draconic Evolution, the pack crashed

**To Reproduce**
1. Go to 'quest book'
2. Click on 'Draconic Evolution chapter'
. See error

**Screenshots**

**Versions (please complete the following information):**
- Modpack version: 0.1.0
- Server?: No

**Additional context**
Add any other context about the problem here. [e.g. Own mods added?]

**Crash Report / log**
Please upload the Crash report or the latest.log file
[hs_err_pid17124.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/9172427/hs_err_pid17124.log)

**Comment by MundM2007** [comment]
Try to restart and Open the Quest book again and after that reupdate the modpack and restart again, this is a known issue but i have No Idea in how to fix this. Mostly it helped to do the thinks stated above. Tell me if this helps
