### ISSUE TITLE
[BUG] ...Duplication Glitch

### ISSUE THREAD

**Issue by PythonSharpPlus** [MundM2007/Ultimate-Progression-Sky#20]
**Describe the bug**
By picking up the barrel it puts dirt on ground and keeps in barrel which duplicates the dirt

**To Reproduce**
1. Go to Any barrel
2. Fill it with compost to get dirt
3. Get close to it and shift right click to pick up the dirt in the style of holding it but not entering your inventory (idk which mods adds this)
4. When picking up the barrel it keeps its nbt data and holds the dirt however because you right clicked it also puts dirt on the ground so by spam Shift-right clicking you get infinite dirt (I'm not far enough in the pack to know if this works with other items)

**Expected behavior**
Either pick up the barrel and give you the dirt removing it from the barrel or removing the dirt and not picking up barrel or picking up barrel and keeping dirt in barrel. Not duplicating dirt

**Screenshots**

**Versions (please complete the following information):**
- Modpack version: 1.2.1
- Server?: No

**Additional context**
Add any other context about the problem here. [e.g. Own mods added?] I just downloaded the pack and played it no extra downloads

**Comment by PythonSharpPlus** [comment]
Update: yes it works with all items that can go in barrels

**Comment by MundM2007** [comment]
Sadly I can't replicate this, when I shift right click on the dirt it will instantly enter my inventory.  Also what do you mean with pickup? mine it, because if you mine it it drops it's items? use carryon?

**Comment by PythonSharpPlus** [comment]
Yes by using carryon mod to pick up the barrel with an item such as dirt in it it allows you to hold that barrel however from what I can tell the game thinks you took the dirt out of the barrel and it falls on the ground for you to pick up. So then you get dirt in your inventory and also still inside the barrel. Some other things that might help with recreating are getting very close to the barrel and shift right clicking on the side faces of the barrel instead of the top or bottem sides idk if the different sides would make a difference I dont think they do.

**Comment by MundM2007** [comment]
I don't understand how you get items to drop from the barrel. If I pick it up with carryon all items stay inside and nothing drops on the ground.

**Comment by MundM2007** [comment]
@PythonSharpPlus

**Comment by PythonSharpPlus** [comment]
very sorry about the late response, it may have been something just with my computer I tried this again when I was closer to the end of the pack and it was no longer working, I have no idea what could have been causing this I also tried this in other packs and it also didn't work sorry,

**Comment by Ragnaros333** [comment]
Same thing happened to me.

**Comment by MundM2007** [comment]
Do you mean exnihilo Barrels? I thought you meant Minecraft Barrels. Yeah then it works, will benfixed in the next update though only in new worlds
