### ISSUE TITLE
[CRASH] Just Downloaded The 1.2.1 Version modpack off forge and went to go run it and i click play it loads up then crashes

### ISSUE THREAD

**Issue by shadow0545** [MundM2007/Ultimate-Progression-Sky#22]
**Describe the Crash**
Minecraft starts up to load the mods and not even 5 secs later I get error code 1 crash.
**To Reproduce**
Run the modpack

**Screenshots**

**Versions (please complete the following information):**
- Modpack version: 1.2.1
- Server?: No

**Additional context**
Nothing Added
**Crash Report / log**
Please upload the Crash report or the latest.log file
[latest.log](https://github.com/MundM2007/Ultimate-Progression-Sky/files/11861204/latest.log)

**Comment by MundM2007** [comment]
This seems like an error with your java or forge installation. Please run repair installation and/or repair profile if using the curseforge app. If you're not using the curseforge app, please try to reinstall the modpack.

**Comment by MundM2007** [comment]
@shadow0545
