### ISSUE TITLE
Unable to get Zombified Piglin Seeds

### ISSUE THREAD

**Issue by LeChercheurYT** [MundM2007/Ultimate-Progression-Sky#23]
**Describe the bug**
The soul jar to obtain the Zombified Piglin Seeds has tags that seem incorrect which prevents it from being crafted.

Otherwise good job 👌

**Versions (please complete the following information):**
- Modpack version: 1.2.2
- Server?: No

**Additional context**
The modpack is original (so not modified by me) 😉

**Comment by MundM2007** [comment]
I have already noticed this and reported this to Industrial agriculture. https://legacy.curseforge.com/minecraft/mc-mods/industrial-agriculture/issues Though I can't get the soul jar to fill. What did you do to achieve this? as then I could possibly fix the recipe

**Comment by LeChercheurYT** [comment]
Hello, unfortunately I haven't found where the problem comes from despite the fact that I searched all the files... but if I find the solution, I will write it down here.

**Comment by MundM2007** [comment]
fixed, with a wierd workaround on my side on the newest version
