### ISSUE TITLE
[BUG][Environmental Core][Refined storage] Null IO component not recognized by autocrafting 

### ISSUE THREAD

**Issue by Mexolius** [MundM2007/Ultimate-Progression-Sky#24]
**Describe the bug**
The Null IO component (from environmental core) is not recognized as the same item as required by any crafting when used in refined storage grid

**To Reproduce**
1. Create autocrafting setup using refined storage grid (in my case using iron crafter from extra storage)
2. Provide a pattern to craft Null IO (from env core)
3. Provide a pattern to craft Item IO (from env core) [or any other IO block from env core]
4. Attempt autocrafting of Item IO
5. Autocrafting should show missing Null IO item despite having a pattern in craft
5b. Autocrafting should still fail if the Null IO item is present in the grid (ex from manual crafting) (see screen below)

**Expected behavior**
The user is able to start autocrafting provided enough resources and patterns present.

**Screenshots**
Same item both present in grid and craftable - 4 blocks are the same that the one shown to be craftable
![image](https://github.com/MundM2007/Ultimate-Progression-Sky/assets/39342674/ba6f9906-1a26-4f72-a5be-42762c42bafb)

Craftable item present in grid hides the craft option [**Correct behaviour**]
![image](https://github.com/MundM2007/Ultimate-Progression-Sky/assets/39342674/72f35f21-8b9a-41a6-a222-7dc6738a31b0)

**Versions (please complete the following information):**
- Modpack version: 1.2.4
- Server?: No

**Additional context**
Add any other context about the problem here. [e.g. Own mods added?]

**Comment by MundM2007** [comment]
Finally got around to check this out, as I'm working on an update. I can't seem to recreate this. If anybody else has more info please say so. What I did: 
1. build an ME System with crafter
2. made a Null IO Pattern, by using the move items from Jei
3. did the same with for Item Output Pattern
4. tried crafting, it works and shows the correct items, the Null IO autocrafted correctly replaces the auto craft and can also be used in the Item Output craft
5. What I noticed though, is that if you use the Null IO from the creative inv, it doesn't work

**Comment by MundM2007** [comment]
wait nvm no it doesn't work anymore even though I changed nothing

**Comment by MundM2007** [comment]
seems like that not using exact mode fixes this

**Comment by Mexolius** [comment]
I think something is weird with refined and nbt. I noticed the same issue with different mods of different modpacks. I'll try out the solutions of non-exact mode next time i Play something. Thanks for your time and solution

**Comment by MundM2007** [comment]
np, I think what exact mode means is just that it follows the exact nbt. And for some reason these blocks from environmental tech have really wierd nbt and this causes these problems
