### ISSUE TITLE
[BUG] Unable to create a "Quantum Entangled Signularity".

### ISSUE THREAD

**Issue by DragoNiiSan** [MundM2007/Ultimate-Progression-Sky#25]
**Describe the bug**
This item is only created when dropping a Ender Dust and a singularity from AE2. If you make a Emendatus Enimatica ender dust, which all of the mods make this ender dust, it will not work as it requires the ender dust from AE2. 

**To Reproduce**
1. Go grab an Ender Dust from Emendatus Enimatica, Singularity from AE2, and TNT. 
2. Drop both, place TNT close enough for explosion and light it. 
3. It will not work. 
It will work if:
1. Do all again, but use Ender Dust from AE2.

**Screenshots**

**Versions (please complete the following information):**
- Modpack version: 1.2.4
- Server?: No - Self-hosted server with ESSENTIAL, but it shouldn't matter. 

**Additional context**
ESSENTIAL, Hosting and cosmetics mod

**Comment by DragoNiiSan** [comment]
the only way to make a Quantum Entangled Signularity is to go into creative and drop it, which requires cheats. 

an idea would be to make it so all the end dust can be convertible in a crafting table into other ender dust mods.

**Comment by MundM2007** [comment]
I think you can use normal ender pearls to, though I think I will adjust the recipe next update
