### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by BloomExists** [MundM2007/Ultimate-Progression-Sky#29]
**Question**
...What's the Mod that adds bigger Oak Trees?

**Comment by MundM2007** [comment]
It's oh the the biomes you'll go. The corresponding feature request was never realized https://github.com/Potion-Studios/BYG/issues/645
to fix the growing of them:
> The world spawn is at y-level 65. Build yourself up above the dirt block to y72 and place a block on top of the last block (so the block now sits on the bottom half of y73).
