### ISSUE TITLE
[BUG] Mesh recipes past the basic tier are broken?

### ISSUE THREAD

**Issue by tangolikeelk** [MundM2007/Ultimate-Progression-Sky#30]
**Describe the bug**
When attempting to craft flint meshes or beyond, the recipes only show recipes using Create contraptions.

**To Reproduce**
1. Go to crafting table
2. Put string mesh in the middle, with 3 flint on each side 
3. See error

**Expected behavior**
Flint mesh should be able to be crafted

**Versions (please complete the following information):**
- Modpack version: 1.2.6
- Server?: No

**Additional context**
I have not added or removed any mods. If this is intended behavior, please let me know.

**Comment by MundM2007** [comment]
this is correct behaviour. The recipes have been modified
