### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by Dasffion** [MundM2007/Ultimate-Progression-Sky#8]
**Describe the bug**
Nether Portal does not light

**To Reproduce**
1. Form Nether portal, 4x5x1
2. Light with Flint and Steel

**Expected behavior**
Nether Portal Lights

**Screenshots**

**Versions (please complete the following information):**
- Modpack version: 0.1.1
- Server?: No

**Additional context**
I double and triple checked the quest book and the patchouli book. I don't see anything about how to get to the nether or something saying that it's disabled.
![2022-08-09_22 55 52](https://user-images.githubusercontent.com/43814155/183801234-bdcbc5a0-64f8-44c4-aab8-d6af6f8420b2.png)

**Comment by MundM2007** [comment]
This is intentional and you aren't supposed to Go to the Nether, though i could add Info to the First Quest you complete
