### ISSUE TITLE
Chiseled blocks versions not avalible

### ISSUE THREAD

**Issue by Arceus73** [MundM2007/Ultimate-Progression-Sky#9]
Is there a reason for the chisel not working? Because when you put in for example deepslate or Basalt it shows no options to chisel. And also in the jei if you check for the chiseled block version's recipes there are non.

**Comment by MundM2007** [comment]
deepslate doesn't have any chisel versions and about basalt, it's a different type of basalt which normaly generates in the overworld and is chisels basalt. i can add a recipe to it though
